apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-web-v1
  labels:
    kubernetes.azureauthority.in: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-web
      version: v1
  template:
    metadata:
      labels:
        app: todolist-web
        version: v1
    spec:
      containers:
        - name: app
          image: nick1950/todo-list-web:1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-lab-v2
  labels:
    kubernetes.azureauthority.in: deployments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-lab
      version: v2
  template:
    metadata:
      labels:
        app: whoami-lab
        version: v2
    spec:
      containers:
        - name: app
          image: sixeyed/whoami:21.04
          env:
            - name: WHOAMI_MODE
              value: q